[build]
  command   = "CI= GENERATE_SOURCEMAP=false npm run build"
  publish   = "build"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  REACT_APP_ENV      = "production"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
